{% set name = "flask_simplelogin" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_simplelogin-{{ version }}.tar.gz
  sha256: a1fb73b7fb37001093d76efc582b085eedc4fca8727a64082ae3f6421411c649

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click
    - flask >=0.12
    - flask-wtf
    - python

test:
  imports:
    - example
    - flask_simplelogin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cuducos/flask_simplelogin
  summary: Flask Simple Login - Login Extension for Flask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
