{% set name = "flask_simplelogin" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_simplelogin-{{ version }}.tar.gz
  sha256: a99b7ded371aa0f5ecf3271c160e3fd52653abd5d879acf9ae621c4825345a8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.5
  run:
    - click
    - flask >=0.12
    - flask-wtf
    - python >=3.5

test:
  imports:
    - flask_simplelogin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cuducos/flask_simplelogin
  summary: Flask Simple Login - Login Extension for Flask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
